### ISSUE TITLE
SLC Deployer: Add timeout option to CLI

### ISSUE THREAD

**Issue by ckunki** [exasol/python-extension-common#52]
In the scope of ticket #50 a new `ExtractValidator` has been implemented.

The current ticket requests adding options to the CLI so that an interactive user can control the timeout duration.

Proposal: 
```python
@click.option('--extract-timeout-minutes', type=int, default=10)
```

Open question:
* Should the CLI specify a default-callback?
* Should the CLI enable to select a callback?

**Comment by ahsimb** [comment]
How would interactive users know what the timeout value should be?
I don't think this option is necessary. It will just clog the documentation.

**Comment by tkilias** [comment]
@ahsimb this option makes actually sense, because the time to wait depends on a lot of factors. And, not all of them we have under control or can detect.

Factors

- Size of SLC
- Files in SLC
- Nodes in Cluster
- type of BucketFS (SaaS or on-prem)
- hardware (CPU speed, disk speed, network speed)

**Comment by ckunki** [comment]
I agree to both comments: this option makes sense in my eyes, but still the users won't know what the timeout value should be in advance. Bad situation. 

I personally would prefer having a way to adjust the timeout than having no way.
